name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Kuroshi7
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generate contribution snake"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Push to output branch
        run: |
          git fetch
          git switch --orphan output
          git reset
          git add dist/github-contribution-grid-snake.svg
          git commit -m "snake"
          git push -f origin output
